name: Build and test

on:
  push:
    branches:
      - master
      - tmp
  pull_request:

jobs:
  cross:
    name: Cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - mips-unknown-linux-gnu
          - arm-linux-androideabi

    steps:
    - uses: actions/checkout@master

    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install cross
      run: cargo install cross

    - name: check
      run: cross check --target ${{ matrix.target }}

    - name: test
      run: cross test --target ${{ matrix.target }}
